version: 0.2

environment_variables:
  plaintext:
    SECRET_KEY: nosecret

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y curl wget python-pip python-dev build-essential binutils libproj-dev gdal-bin
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python manage.py test --noinput -v 3
  post_build:
    commands:
      - echo Build completed on `date`
